[build]
  base    = "paisa-budget"
  command = "npm install && npx ng build --configuration production"
  publish = "dist/paisa-budget/browser"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
